@extends('Admin.Layouts.default')

@section('styles')
    <link rel="stylesheet" href="{{ asset_resource('assets/css/admin-logs-overrides.css') }}?v=20260925-1">
@stop

@section('content')
    <div class="al-page">
        <div class="al-page__header">
            <div class="al-page__title-group">
                <div class="al-page__title-icon"><i class="fas fa-file-export"></i></div>
                <div>
                    <h1 class="al-page__title">{{ trans('admin.'.$section) }}</h1>
                    <p class="al-page__subtitle">Reports generated by schedules and sent to your email</p>
                </div>
            </div>

            <div class="al-page__actions">
                <span class="al-toolbar__count">{{ number_format($logs->total()) }} reports</span>
            </div>
        </div>

        <div class="al-card" id="table_{{ $section }}">

            <div class="al-toolbar">
                <div class="al-search">
                    <i class="fas fa-search"></i>
                    {!! Form::text('search_phrase', null, [
                            'class' => 'form-control',
                            'placeholder' => trans('admin.search_it'),
                            'data-filter' => 'true']) !!}
                </div>

                <div class="lg-filters">
                    <div class="lg-filter lg-filter--send">
                        {!! Form::select('is_send[]', ['1' => trans('global.yes'), '0' => trans('global.no')], null, [
                                'class' => 'form-control',
                                'multiple' => 'multiple',
                                'title' => trans('global.is_send'),
                                'data-filter' => 'true']) !!}
                    </div>
                </div>
            </div>

            <div class="panel-body" data-table>
                @include('Admin.'.ucfirst($section).'.table')
            </div>
        </div>
    </div>
@stop

@section('javascript')
<script>
    tables.set_config('table_{{ $section }}', {
        url:'{{ route("admin.{$section}.index") }}',
        prompt_delete_url:'{{ route("admin.{$section}.destroy") }}',
        prompt_delete_all_url: '{{ route("admin.{$section}.destroy", ['all' => 1]) }}',
        _models: new Array('report_logs')
    });
</script>
@stop
